---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      alertmanagerSpec:
        alertmanagerConfiguration:
          name: cardellinotech
      ingress:
        enabled: false
    kubeProxy:
      enabled: false
    prometheus:
      ingress:
        enabled: false
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1024Mi
          cpu: 500m
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: "node-exporter"
            honor_timestamps: true
            static_configs:
              - targets:
                  - 172.18.65.5:9100
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: hcloud-volumes
              resources:
                requests:
                  storage: 10Gi
    nodeExporter:
      enabled: true
    prometheus-node-exporter:
      fullnameOverride: node-exporter
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
    kubeStateMetrics:
      enabled: true
    grafana:
      enabled: false
      forceDeployDashboards: true
    kubeControllerManager:
      service:
        port: 10252
        targetPort: 10252
      serviceMonitor:
        https: false
        insecureSkipVerify: true
    kubeEtcd:
      service:
        port: 2381
        targetPort: 2381
    kubeScheduler:
      service:
        port: 10251
        targetPort: 10251
      serviceMonitor:
        https: false
        insecureSkipVerify: true