apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujx2mzt4ere2wmnzrmu9rlt4f57jgaw50tka4uljcs9ffhm30fcs0u4kyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaWo3Q2s3bGhjTmZ2RFc2
            Znl1TnZGRGdBTE93ZnFSOTFTeWI0QnhSSVdjCm5tTW5DYlBHNG95N1BlWDNmS2pL
            TitFbkZlS1FQQjFqcGRHZk5FYnVTWkUKLS0tIE5YWWVNWkN2L1lDMFB2WFg2NTQ1
            SW4zbEowby81ZGVXTDlxMWxZQWhObXcKU7YpkMWsNl+KUL8ws11tbxL+Dm35C1TF
            1wHTOtLTPHe5rBLNkVKM8ASyQPjAuAQTj58x3duoEu/Z0jeedBQcLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-06T07:49:50Z"
    mac: ENC[AES256_GCM,data:9S8womDJYp36anRckXBWWETHX55cilbMTpcmATlS+u/BKWjX0T/1LL5ajctSD9RPqJhyxEQ8znYAZ5Gyit6vY863RhFf9Irp3rvEgdO/t1X0TmXOcY7m1HqlquPNf2mUnAqE5TKmwoyG+r7oldFXMCTrTt38TOuVN56rgocEzdA=,iv:agLy8Mn27GA18Kd7oQyFnRxkrUZy2PuO98cqC4HrakU=,tag:SM7r+9QYxaAlvM5MQBV7rQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
