apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    slackApiURL: ENC[AES256_GCM,data:IsF7efYeMuzn9y4j+vKo+dgxQgOVVhHsnFqNXdP6beVVHcrB6NmDZMvPfrCxaorMfmP5zg3gncK5SsnfBYQYXaJds3ty03ab3GZJATjOIrzS,iv:uHKzclizKeDhUQ/Syt4vwTnCstXx0xJEqQGBtTE4+L0=,tag:+mgdfllj51DbuMsZ6hv17A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujx2mzt4ere2wmnzrmu9rlt4f57jgaw50tka4uljcs9ffhm30fcs0u4kyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabVQ0NHQzYUptaVpSbzVo
            Ty9pamY1Mkt1bG1Qa1VLVGRSZnMwZklLV3g4Ckg2M3ZrdmxmV21WQVlWZzYvbytz
            Q2drdXJmbTNpTnB2V2NSWFJsVDZCSWsKLS0tIEJmOFYrRHZvaWlLdnpEVjRFTXQ2
            SWs2Zk9qN0hiTWdoWnhPS2hVZWtGTGcKSqDOUvgTYPqXQQZhI8828QWPPLg3BkmF
            d9abnNzA/jpRsmAt6SifzsQL1KvCrO/u0NwhQ7TOzcNinyQANMeY8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T16:57:13Z"
    mac: ENC[AES256_GCM,data:kGoY3OwOKRUCnfeuzuvb5IXmMqLJ96ki014KzJbAyMwMf/UP3UQoZZxLiHVohcJJFv2vxDHGhyQELmCjV9CTjAKgC9SYFMTyEd64E4e89Aqo4aT/jzT4v66fVOGpNGoeSjUZFPkzUEsO9zb+WjZ70MTfWvlE8QPYRXoqcbr3xqo=,iv:29g2tcVGguPBqvTLutgZryVLCBChMEMETmGk/dGTn04=,tag:lBzQx/9/KUso2yT+XiEUFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
