apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:yX3ZOFMWuXnls4OO5CkGxKs/ubNiuzg=,iv:QVHMrqIvczt38wZOgzYFuPgD0qN+tz22HEWrhKfQkJ0=,tag:giWLgAynyjnFjN41XqmgtA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:EUrqU3hTYZE9jJyuM5K22GbE6eCtwwFC6rCZrshDz1naMbUY,iv:xmq9ip6EtO32DBJKfsbA1+a+odhlquwOcBlh/If+YAc=,tag:lKPvLGO3MdaSIuimUc0urQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:VOnOAW/5EQ4HAnVQ/HLc,iv:b3m2IYvc0bXmKaFxeqgteYGv+Y+irIWcjOBpTx/7JtI=,tag:R2avkhZH7BrYFPB2btswMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujx2mzt4ere2wmnzrmu9rlt4f57jgaw50tka4uljcs9ffhm30fcs0u4kyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMG9UN1g0c1lZZ2lXTGM5
            QkMxRlJ2cytzeHZLc3pnSkx1bFc2Z2xIRTFVCm1pSitPakNjcVFLUU1NdlZ5aHEy
            OFBvL1hCeUR2SnZaQ2tPeE5CcnhXTmMKLS0tIGN6WW5KMWhPWlVIRWE1WnJUM1A0
            RFlxd3VUbzN6SCtrWTVjc3BjWW92WEEKj6YxL3gvifeHKZ6N0UU4FdDj0rm7n+JE
            947M+u8UGV0eM7c0Vosafkk3fttdkS5EshulD2OFd9UkSzbzP8WRRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-05T14:46:55Z"
    mac: ENC[AES256_GCM,data:TMWRo/qyHFy1aJWiVkh0JybTzbQ194qxQ3/YxjRyFEkM6y10MSK+v+V1+k2xR4l5j/PTfCJX/R0p5wpWfVhupfOJ3/ezP6HL4ppqOK+Zv+zNu43lzvy6c5xuX0A+XlZc9rxm5+Bg8eQm14BmUPBCLaI934g2hV5eXnAT2EaPV3Q=,iv:hiiRmu5TDRF0n3EIGwE0CZ+dnYQO0a2Nz42GzLmqyS0=,tag:dU1YCN+g5GW+zZhjb9b7Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
