apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:48m4OmqH1lc1uqH6,iv:a4H0QpuShe+2QaI77YUSZNlmrcTAkoAIacqJfbVb8ak=,tag:qwfbaR6fV5GV+7CnisyToQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujx2mzt4ere2wmnzrmu9rlt4f57jgaw50tka4uljcs9ffhm30fcs0u4kyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cGhBa0dhd3VUVGNEOENT
            QjdTZ1BNa0FCRytOck52Qm51dnBHMXNCN1NZCkR1V09nQmNNa3UrNEU4T1Q4Z2p0
            ZHZwdUx2eWoyRVZ5eHpmNURSR2dUSDQKLS0tIGczL3JZMnJIcGVzV1ZQUi9iV29q
            RzhlekJjYVFhTXJRYVFQbkJ3bSsrVlkKeoyb0KwK/JAW6ImQhlLB2Dv43H6eZHus
            DnTA5vgpLMySgdCxXh9Sul3DJl8Wx5IpPzRa8HEvVKGHEbpEKJlPVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-05T14:46:55Z"
    mac: ENC[AES256_GCM,data:xL9Op/nfVlX2RLsQDZZMi2HAOwdJjLNvMQL47BbwdLioS5GUco7bQdQjK47ZDFv8hYgfRzmhmpVlWpskeqokxZf4H2bqIwVByNNXEYd5CSfCI2AMgm4TpKsERIPAPAmV/jNRct9b1mr4ixs8BZMjpcRpnMsdn2CeM5CbC4/7rNE=,iv:VQHYBRfcaEUSB3F6a0W5xMfRcu8J0y83+rfcDB6qoRw=,tag:36ck6X9rbtSpvFof2I2/Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
