apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:T7xzCYv36BBxIpME26xIczyLd2OSas4=,iv:VnFDMmK3XwV8CP5ljThM04gNwHnmSTE4TEF2tUzbp/s=,tag:CFJmSWzJuQmYP+LDUDyhqA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:GjqFyut+5tn21fzpf+cG,iv:TOvoFmjO8/MCVhumGnPabkL7QSegZedG/h7ztIWuyS0=,tag:a1HGypH/xbbUXKQBCsCJbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ujx2mzt4ere2wmnzrmu9rlt4f57jgaw50tka4uljcs9ffhm30fcs0u4kyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd0JyMXAyZ3RMcmNSNFdu
            Tlg2OHFzWHNicnJ3bWFUem5scjh5SDFWdUJVCjlEWDVLOThiNTdPbVM0VHFIMy9w
            a3FmWnNmRElzQWM0M1RtaXFCQVZ6b3cKLS0tIEU0bC9wU1d6eVpmbmNGaUZGZ1pn
            TzdjOFRGSDI2WUNYVlhSdVg3aEh5SXcKyskDQwhh/UgKOr9pDpxgBKD7/xI6Oq/j
            zDFDui3fadKJhe4EXnJ8r22Wf2AKRjknjA8a6qGruY37LHWi+0q+Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-06T07:49:50Z"
    mac: ENC[AES256_GCM,data:orBQT8UwN7BSS9zwnuAGy+8GcDKVp526cN/FSAKD3zvZfwBhoCJW11sHgKsqE9X/ZY3XWLkU8qvY5xX6La5ABjUHForsuFmYN3dX5ZWr9TV43YAnU3nPf3dlGsd5R6Cc33kmBq2/j317GSYhA4xuoHN4e3RGTPNjyPFhrSM7noc=,iv:qUIPaJy1kn0hxHt9lSlmd2DINFkv8RBD1LLTwU6VoGA=,tag:8Ud/9pvR0koWX2T8rvJU1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
