---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultBackend:
      enabled: true
    controller:
      replicaCount: 3
      electionID: ingress-controller-leader-private
      watchIngressWithoutClass: true
      service:
        annotations:
          load-balancer.hetzner.cloud/network-zone: "eu-central"
          load-balancer.hetzner.cloud/use-private-ip: "true"
          load-balancer.hetzner.cloud/ipv6-disabled: "true"
          load-balancer.hetzner.cloud/disable-private-ingress: "false"
          load-balancer.hetzner.cloud/disable-public-network: "true"
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-private
        default: false
        enabled: true
        name: nginx-private
